version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
#      - "db_volume:/var/mysql" - не правильный путь, не сохраняет БД
      - "db_volume:/var/lib/mysql"
    networks:
      - php_advanced

#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 8080:8080
  app:
#    image: "php:8.1-apache"
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - php_advanced