version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  db:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres2
    ports:
      - "5432:5432"
    volumes:
      - "db_volume:/var/lib/pgsql"
    networks:
      - php_advanced

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - php_advanced

  app:
#    image: "php:8.1-apache"
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "83:80"
    networks:
      - php_advanced