version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  db:
#    image: "postgres:14"
    image: "mysql:8"
    restart: always
    environment:
#      POSTGRES_ROOT_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
#      - 5432:5432
    volumes:
#      - "db_volume:/var/pgsql"
      - "db_volume:/var/mysql"
    networks:
      - php_advanced

#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 8080:8080
  app:
    image: "php:8.1-apache"
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "81:80"
    networks:
      - php_advanced